const { test, expect, fixture, login, noOverflow } = require('./support/helpers');

test('analysis starts only on click, continues after reload, retries errors, and resets', async ({ page }, info) => {
  await login(page);
  await expect(page.getByRole('button', { name: 'Analyze my posture', exact: true })).toHaveCount(0);
  fixture('coach', 'available');
  await page.goto('/coach');
  const requests = [];
  page.on('request', request => { if (request.method() === 'POST' && new URL(request.url()).pathname === '/coach') requests.push(request.postDataJSON()); });
  await expect(page.getByRole('button', { name: 'Analyze my posture', exact: true })).toBeVisible();
  expect(requests).toHaveLength(0);
  await page.getByRole('button', { name: 'Analyze my posture', exact: true }).click();
  await expect(page.locator('.muse-thread')).toContainText('What were you doing while wearing it?');
  expect(requests[0].intent).toBe('analyze');
  await page.reload();
  await expect(page.locator('.muse-thread')).toContainText('What were you doing while wearing it?');
  await page.getByLabel('Your message to Muse').fill('Coding on the couch');
  await page.getByRole('button', { name: 'Send', exact: false }).click();
  await expect(page.locator('.muse-thread')).toContainText('Try one comfortable change');
  expect(requests[1].intent).toBe('chat');
  await noOverflow(page);
  await page.getByText('How your conversation is shared', { exact: true }).click();
  await expect(page.locator('.coach-sharing')).toContainText('slouch share');
  await expect(page.locator('.coach-sharing')).toContainText('no reminders');
  await info.attach('muse-analysis-dark.png', { body: await page.screenshot({ fullPage: true }), contentType: 'image/png' });
  await page.getByRole('button', { name: 'Switch to light mode' }).click();
  await expect(page.locator('.tracker')).toHaveCSS('color', 'rgb(5, 30, 57)');
  await noOverflow(page);
  await info.attach('muse-analysis-light.png', { body: await page.screenshot({ fullPage: true }), contentType: 'image/png' });
  await page.getByRole('button', { name: 'New chat', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Send', exact: false })).toBeEnabled();
  await expect(page.locator('.muse-thread')).not.toContainText('Try one comfortable change');
  fixture('coach', 'unavailable');
  await page.getByRole('button', { name: 'Analyze my posture', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Muse is not connected');
  await expect(page.getByLabel('Your message to Muse')).toHaveValue('Analyze my posture');
  fixture('coach', 'available');
  await page.getByRole('button', { name: 'Send', exact: false }).click();
  await expect(page.locator('.muse-thread')).toContainText('What were you doing while wearing it?');
  expect(requests.at(-1).intent).toBe('analyze');
});
